/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_clustering_KMeansDALImpl */

#ifndef _Included_com_intel_oap_mllib_clustering_KMeansDALImpl
#define _Included_com_intel_oap_mllib_clustering_KMeansDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_clustering_KMeansDALImpl
 * Method:    cKMeansDALComputeWithInitCenters
 * Signature: (JJIDIIIZ[ILorg/apache/spark/ml/clustering/KMeansResult;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_mllib_clustering_KMeansDALImpl_cKMeansDALComputeWithInitCenters
  (JNIEnv *, jobject, jlong, jlong, jint, jdouble, jint, jint, jint, jboolean, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
