/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_datamanagement_data_DataDictionary */

#ifndef _Included_com_intel_daal_datamanagement_data_DataDictionary
#define _Included_com_intel_daal_datamanagement_data_DataDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_daal_datamanagement_data_DataDictionary
 * Method:    init
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_datamanagement_data_DataDictionary_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_intel_daal_datamanagement_data_DataDictionary
 * Method:    cSetNumberOfFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_DataDictionary_cSetNumberOfFeatures
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_daal_datamanagement_data_DataDictionary
 * Method:    cGetNumberOfFeatures
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_datamanagement_data_DataDictionary_cGetNumberOfFeatures
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_datamanagement_data_DataDictionary
 * Method:    cSetFeature
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_DataDictionary_cSetFeature
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_intel_daal_datamanagement_data_DataDictionary
 * Method:    cSetAllFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_DataDictionary_cSetAllFeatures
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_daal_datamanagement_data_DataDictionary
 * Method:    cResetDictionary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_DataDictionary_cResetDictionary
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_datamanagement_data_DataDictionary
 * Method:    cGetCDataDictionaryFeaturesEqual
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_datamanagement_data_DataDictionary_cGetCDataDictionaryFeaturesEqual
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_datamanagement_data_DataDictionary
 * Method:    cGetIndexType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_datamanagement_data_DataDictionary_cGetIndexType
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
