/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_data_management_data_DataDictionary_FeaturesEqual */

#ifndef _Included_com_intel_daal_data_management_data_DataDictionary_FeaturesEqual
#define _Included_com_intel_daal_data_management_data_DataDictionary_FeaturesEqual
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_daal_data_management_data_DataDictionary_FeaturesEqual__notEqual
#define com_intel_daal_data_management_data_DataDictionary_FeaturesEqual__notEqual 0L
#undef com_intel_daal_data_management_data_DataDictionary_FeaturesEqual__equal
#define com_intel_daal_data_management_data_DataDictionary_FeaturesEqual__equal 1L
#ifdef __cplusplus
}
#endif
#endif
