/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_stat_CorrelationDALImpl */

#ifndef _Included_com_intel_oap_mllib_stat_CorrelationDALImpl
#define _Included_com_intel_oap_mllib_stat_CorrelationDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_stat_CorrelationDALImpl
 * Method:    cCorrelationTrainDAL
 * Signature: (JIII[ILcom/intel/oap/mllib/stat/CorrelationResult;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_mllib_stat_CorrelationDALImpl_cCorrelationTrainDAL
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
