/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_recommendation_ALSDALImpl */

#ifndef _Included_com_intel_oap_mllib_recommendation_ALSDALImpl
#define _Included_com_intel_oap_mllib_recommendation_ALSDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_recommendation_ALSDALImpl
 * Method:    cDALImplictALS
 * Signature: (JJIIDDIIILcom/intel/oap/mllib/recommendation/ALSResult;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_mllib_recommendation_ALSDALImpl_cDALImplictALS
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jdouble, jdouble, jint, jint, jint, jobject);

/*
 * Class:     com_intel_oap_mllib_recommendation_ALSDALImpl
 * Method:    cShuffleData
 * Signature: (Ljava/nio/ByteBuffer;IILcom/intel/oap/mllib/recommendation/ALSPartitionInfo;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_oap_mllib_recommendation_ALSDALImpl_cShuffleData
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
