/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_datamanagement_data_DataFeatureUtils_VectorDownCastFloat2Double */

#ifndef _Included_com_intel_daal_datamanagement_data_DataFeatureUtils_VectorDownCastFloat2Double
#define _Included_com_intel_daal_datamanagement_data_DataFeatureUtils_VectorDownCastFloat2Double
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
