/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oneapi_dal_table_ColumnAccessor */

#ifndef _Included_com_intel_oneapi_dal_table_ColumnAccessor
#define _Included_com_intel_oneapi_dal_table_ColumnAccessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oneapi_dal_table_ColumnAccessor
 * Method:    cPullDouble
 * Signature: (JJJJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_intel_oneapi_dal_table_ColumnAccessor_cPullDouble
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     com_intel_oneapi_dal_table_ColumnAccessor
 * Method:    cPullFloat
 * Signature: (JJJJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_intel_oneapi_dal_table_ColumnAccessor_cPullFloat
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     com_intel_oneapi_dal_table_ColumnAccessor
 * Method:    cPullInt
 * Signature: (JJJJ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_intel_oneapi_dal_table_ColumnAccessor_cPullInt
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);


#ifdef __cplusplus
}
#endif
#endif
