/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oneapi_dal_table_SimpleMetadataImpl */

#ifndef _Included_com_intel_oneapi_dal_table_SimpleMetadataImpl
#define _Included_com_intel_oneapi_dal_table_SimpleMetadataImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oneapi_dal_table_SimpleMetadataImpl
 * Method:    cGetDataType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_intel_oneapi_dal_table_SimpleMetadataImpl_cGetDataType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_oneapi_dal_table_SimpleMetadataImpl
 * Method:    cGetFeatureCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_SimpleMetadataImpl_cGetFeatureCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_SimpleMetadataImpl
 * Method:    cGetFeatureType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_intel_oneapi_dal_table_SimpleMetadataImpl_cGetFeatureType
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
