/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl */

#ifndef _Included_com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
#define _Included_com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl_maxBufferSize
#define com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl_maxBufferSize 2147483647LL
/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    dInit
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_dInit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    sInit
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_sInit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    lInit
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_lInit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    iInit
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_iInit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    dictInit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_dictInit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cAllocateDataMemoryDouble
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cAllocateDataMemoryDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cAllocateDataMemoryFloat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cAllocateDataMemoryFloat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cAllocateDataMemoryLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cAllocateDataMemoryLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cAllocateDataMemoryInt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cAllocateDataMemoryInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getIndexType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getIndexType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getDoubleBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getDoubleBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getFloatBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getFloatBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getLongBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getLongBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getIntBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getIntBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getDoubleBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getDoubleBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getFloatBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getFloatBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getIntBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getIntBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    releaseDoubleBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_releaseDoubleBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    releaseFloatBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_releaseFloatBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    releaseIntBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_releaseIntBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    assignLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_assignLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    assignInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_assignInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    assignDouble
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_assignDouble
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    assignFloat
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_assignFloat
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getDoubleColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getDoubleColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getFloatColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getFloatColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    getIntColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_getIntColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    releaseDoubleColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_releaseDoubleColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    releaseFloatColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_releaseFloatColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    releaseIntColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_releaseIntColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cSetDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cSetDouble
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cSetFloat
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cSetFloat
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cSetLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cSetLong
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cSetInt
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cSetInt
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cGetDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cGetDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cGetFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cGetFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cGetLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cGetLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_HomogenNumericTableByteBufferImpl
 * Method:    cGetInt
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_data_1management_data_HomogenNumericTableByteBufferImpl_cGetInt
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
