/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_datamanagement_data_MergedNumericTableImpl */

#ifndef _Included_com_intel_daal_datamanagement_data_MergedNumericTableImpl
#define _Included_com_intel_daal_datamanagement_data_MergedNumericTableImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    getDoubleBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_getDoubleBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    getFloatBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_getFloatBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    getIntBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_getIntBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    releaseDoubleBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_releaseDoubleBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    releaseFloatBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_releaseFloatBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    releaseIntBlockBuffer
 * Signature: (JJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_releaseIntBlockBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    getDoubleColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_getDoubleColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    getFloatColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_getFloatColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    getIntColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_getIntColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    releaseDoubleColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_releaseDoubleColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    releaseFloatColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_releaseFloatColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    releaseIntColumnBuffer
 * Signature: (JJJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_releaseIntColumnBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    cNewMergedNumericTable
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_cNewMergedNumericTable
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    cGetNumberOfColumns
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_cGetNumberOfColumns
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_datamanagement_data_MergedNumericTableImpl
 * Method:    cAddNumericTable
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_datamanagement_data_MergedNumericTableImpl_cAddNumericTable
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
