/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_data_management_data_NumericTableImpl */

#ifndef _Included_com_intel_daal_data_management_data_NumericTableImpl
#define _Included_com_intel_daal_data_management_data_NumericTableImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cAllocateDataMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cAllocateDataMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cFreeDataMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cFreeDataMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetNumberOfColumns
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetNumberOfColumns
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetNumberOfRows
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetNumberOfRows
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cSetNumberOfRows
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cSetNumberOfRows
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cSetNumberOfColumns
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cSetNumberOfColumns
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cSetNormalizationFlag
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cSetNormalizationFlag
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cIsNormalized
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cIsNormalized
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cSetCDataDictionary
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cSetCDataDictionary
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetDataLayout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetDataLayout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetDataMemoryStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetDataMemoryStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetNumberOfCategories
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetNumberOfCategories
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetIntValue
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetIntValue
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetFloatValue
 * Signature: (JJJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetFloatValue
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetDoubleValue
 * Signature: (JJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetDoubleValue
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_intel_daal_data_management_data_NumericTableImpl
 * Method:    cGetCDataDictionary
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_data_1management_data_NumericTableImpl_cGetCDataDictionary
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
