/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_datamanagement_data_DataFeatureUtils_VectorDownCastDouble2Int */

#ifndef _Included_com_intel_daal_datamanagement_data_DataFeatureUtils_VectorDownCastDouble2Int
#define _Included_com_intel_daal_datamanagement_data_DataFeatureUtils_VectorDownCastDouble2Int
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
