/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_classification_RandomForestClassifierDALImpl */

#ifndef _Included_com_intel_oap_mllib_classification_RandomForestClassifierDALImpl
#define _Included_com_intel_oap_mllib_classification_RandomForestClassifierDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_classification_RandomForestClassifierDALImpl
 * Method:    cRFClassifierTrainDAL
 * Signature: (JJIIIIIIIDDLjava/lang/String;Lcom/intel/oap/mllib/classification/RandomForestResult;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_mllib_classification_RandomForestClassifierDALImpl_cRFClassifierTrainDAL
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jdouble, jdouble, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
