/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oneapi_dal_table_RowAccessor */

#ifndef _Included_com_intel_oneapi_dal_table_RowAccessor
#define _Included_com_intel_oneapi_dal_table_RowAccessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oneapi_dal_table_RowAccessor
 * Method:    cPullDouble
 * Signature: (JJJI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_intel_oneapi_dal_table_RowAccessor_cPullDouble
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     com_intel_oneapi_dal_table_RowAccessor
 * Method:    cPullFloat
 * Signature: (JJJI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_intel_oneapi_dal_table_RowAccessor_cPullFloat
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);


/*
 * Class:     com_intel_oneapi_dal_table_RowAccessor
 * Method:    cPullInt
 * Signature: (JJJI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_intel_oneapi_dal_table_RowAccessor_cPullInt
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
