/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_regression_RandomForestRegressorDALImpl */

#ifndef _Included_com_intel_oap_mllib_regression_RandomForestRegressorDALImpl
#define _Included_com_intel_oap_mllib_regression_RandomForestRegressorDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_regression_RandomForestRegressorDALImpl
 * Method:    cRFRegressorTrainDAL
 * Signature: (JJIIIIIZLjava/lang/String;Lcom/intel/oap/mllib/classification/RandomForestResult;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_intel_oap_mllib_regression_RandomForestRegressorDALImpl_cRFRegressorTrainDAL
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint, jboolean, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
