/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_regression_LinearRegressionDALImpl */

#ifndef _Included_com_intel_oap_mllib_regression_LinearRegressionDALImpl
#define _Included_com_intel_oap_mllib_regression_LinearRegressionDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_regression_LinearRegressionDALImpl
 * Method:    cLinearRegressionTrainDAL
 * Signature: (JJDDIIIILjava/lang/String;Lcom/intel/oap/mllib/regression/LiRResult;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_mllib_regression_LinearRegressionDALImpl_cLinearRegressionTrainDAL
  (JNIEnv *, jobject, jlong, jlong, jdouble, jdouble, jint, jint, jint, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
