/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_datamanagement_data_DataFeatureUtils_VectorUpCastBase2Types */

#ifndef _Included_com_intel_daal_datamanagement_data_DataFeatureUtils_VectorUpCastBase2Types
#define _Included_com_intel_daal_datamanagement_data_DataFeatureUtils_VectorUpCastBase2Types
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
