/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_data_management_data_DataFeatureUtils_IndexNumType */

#ifndef _Included_com_intel_daal_data_management_data_DataFeatureUtils_IndexNumType
#define _Included_com_intel_daal_data_management_data_DataFeatureUtils_IndexNumType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
