/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_classification_NaiveBayesDALImpl */

#ifndef _Included_com_intel_oap_mllib_classification_NaiveBayesDALImpl
#define _Included_com_intel_oap_mllib_classification_NaiveBayesDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_classification_NaiveBayesDALImpl
 * Method:    cNaiveBayesDALCompute
 * Signature: (JJIIILcom/intel/oap/mllib/classification/NaiveBayesResult;)V
 */
JNIEXPORT void JNICALL Java_com_intel_oap_mllib_classification_NaiveBayesDALImpl_cNaiveBayesDALCompute
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
