/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_stat_SummarizerDALImpl */

#ifndef _Included_com_intel_oap_mllib_stat_SummarizerDALImpl
#define _Included_com_intel_oap_mllib_stat_SummarizerDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_stat_SummarizerDALImpl
 * Method:    cSummarizerTrainDAL
 * Signature: (JIIZ[ILcom/intel/oap/mllib/stat/SummarizerResult;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_mllib_stat_SummarizerDALImpl_cSummarizerTrainDAL
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
