/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oneapi_dal_table_CSRTableImpl */

#ifndef _Included_com_intel_oneapi_dal_table_CSRTableImpl
#define _Included_com_intel_oneapi_dal_table_CSRTableImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    iInit
 * Signature: (JJ[I[J[JII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_iInit
  (JNIEnv *, jobject, jlong, jlong, jintArray, jlongArray, jlongArray, jint, jint);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    fInit
 * Signature: (JJ[F[J[JII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_fInit
  (JNIEnv *, jobject, jlong, jlong, jfloatArray, jlongArray, jlongArray, jint, jint);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    dInit
 * Signature: (JJ[D[J[JII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_dInit
  (JNIEnv *, jobject, jlong, jlong, jdoubleArray, jlongArray, jlongArray, jint, jint);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    lInit
 * Signature: (JJ[J[J[JII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_lInit
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jlongArray, jlongArray, jint, jint);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cEmptyCSRTableInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cEmptyCSRTableInit
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetColumnCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetColumnCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetRowCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetRowCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetKind
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetKind
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetDataLayout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetDataLayout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetMetaData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetMetaData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetPullColumnIface
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetPullColumnIface
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetIntData
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetIntData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetLongData
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetLongData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetFloatData
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetFloatData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetDoubleData
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetDoubleData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetColumnIndices
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetColumnIndices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_oneapi_dal_table_CSRTableImpl
 * Method:    cGetRowIndices
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_oneapi_dal_table_CSRTableImpl_cGetRowIndices
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
