/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_mllib_feature_PCADALImpl */

#ifndef _Included_com_intel_oap_mllib_feature_PCADALImpl
#define _Included_com_intel_oap_mllib_feature_PCADALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_oap_mllib_feature_PCADALImpl
 * Method:    cPCATrainDAL
 * Signature: (JIIIILjava/lang/String;Lcom/intel/oap/mllib/feature/PCAResult;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_mllib_feature_PCADALImpl_cPCATrainDAL
  (JNIEnv *, jobject, jlong, jint, jint, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
