/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_regression_LinearRegressionDALImpl */

#ifndef _Included_org_apache_spark_ml_regression_LinearRegressionDALImpl
#define _Included_org_apache_spark_ml_regression_LinearRegressionDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_regression_LinearRegressionDALImpl
 * Method:    cLRTrainDAL
 * Signature: (JJZDDIILorg/apache/spark/ml/regression/LiRResult;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_regression_LinearRegressionDALImpl_cLRTrainDAL
  (JNIEnv *, jobject, jlong, jlong, jboolean, jdouble, jdouble, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
