/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_stat_CorrelationDALImpl */

#ifndef _Included_org_apache_spark_ml_stat_CorrelationDALImpl
#define _Included_org_apache_spark_ml_stat_CorrelationDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_stat_CorrelationDALImpl
 * Method:    cCorrelationTrainDAL
 * Signature: (JIIZ[ILorg/apache/spark/ml/stat/CorrelationResult;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_stat_CorrelationDALImpl_cCorrelationTrainDAL
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
