/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_mllib_stat_SummarizerDALImpl */

#ifndef _Included_org_apache_spark_mllib_stat_SummarizerDALImpl
#define _Included_org_apache_spark_mllib_stat_SummarizerDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_mllib_stat_SummarizerDALImpl
 * Method:    cSummarizerTrainDAL
 * Signature: (JIIZ[ILorg/apache/spark/mllib/stat/SummarizerResult;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_mllib_stat_SummarizerDALImpl_cSummarizerTrainDAL
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
