/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_recommendation_ALSDALImpl */

#ifndef _Included_org_apache_spark_ml_recommendation_ALSDALImpl
#define _Included_org_apache_spark_ml_recommendation_ALSDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_recommendation_ALSDALImpl
 * Method:    cDALImplictALS
 * Signature: (JJIIDDIIILorg/apache/spark/ml/recommendation/ALSResult;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_recommendation_ALSDALImpl_cDALImplictALS
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jdouble, jdouble, jint, jint, jint, jobject);

/*
 * Class:     org_apache_spark_ml_recommendation_ALSDALImpl
 * Method:    cShuffleData
 * Signature: (Ljava/nio/ByteBuffer;IILorg/apache/spark/ml/recommendation/ALSPartitionInfo;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_spark_ml_recommendation_ALSDALImpl_cShuffleData
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
