/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_classification_NaiveBayesDALImpl */

#ifndef _Included_org_apache_spark_ml_classification_NaiveBayesDALImpl
#define _Included_org_apache_spark_ml_classification_NaiveBayesDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_classification_NaiveBayesDALImpl
 * Method:    cNaiveBayesDALCompute
 * Signature: (JJIIILorg/apache/spark/ml/classification/NaiveBayesResult;)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_ml_classification_NaiveBayesDALImpl_cNaiveBayesDALCompute
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
