name: OAP MLlib Code Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Scala code
        run: |
          cd ${{github.workspace}}/mllib-dal
          ${{github.workspace}}/dev/code-checks/lint-scala.sh

      - name: Check Java code
        run: |
          cd ${{github.workspace}}/mllib-dal
          ${{github.workspace}}/dev/code-checks/lint-java.sh

      - name: Check C++ code
        run: |
          cd ${{github.workspace}}/mllib-dal/src/main/native
          ${{github.workspace}}/dev/code-checks/lint-cpp.sh
